// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKL0m_mKVkH8XMtuePQCtIENI1YtnZGY',
    appId: '1:506755248244:web:335314fc48981dd747e121',
    messagingSenderId: '506755248244',
    projectId: 'spotify-clone-ed4b0',
    authDomain: 'spotify-clone-ed4b0.firebaseapp.com',
    storageBucket: 'spotify-clone-ed4b0.firebasestorage.app',
    measurementId: 'G-F00ZF20BT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFXTAi42tv4lsOMEeq493svdjEozPiU0',
    appId: '1:506755248244:android:c7def55b74dc9d2447e121',
    messagingSenderId: '506755248244',
    projectId: 'spotify-clone-ed4b0',
    storageBucket: 'spotify-clone-ed4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAza1fJ2l6omBSX4Flt-YGAm4Oi2McweU',
    appId: '1:506755248244:ios:b4740a2ed1960f3047e121',
    messagingSenderId: '506755248244',
    projectId: 'spotify-clone-ed4b0',
    storageBucket: 'spotify-clone-ed4b0.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAza1fJ2l6omBSX4Flt-YGAm4Oi2McweU',
    appId: '1:506755248244:ios:b4740a2ed1960f3047e121',
    messagingSenderId: '506755248244',
    projectId: 'spotify-clone-ed4b0',
    storageBucket: 'spotify-clone-ed4b0.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRKL0m_mKVkH8XMtuePQCtIENI1YtnZGY',
    appId: '1:506755248244:web:ab919ad1554ee38b47e121',
    messagingSenderId: '506755248244',
    projectId: 'spotify-clone-ed4b0',
    authDomain: 'spotify-clone-ed4b0.firebaseapp.com',
    storageBucket: 'spotify-clone-ed4b0.firebasestorage.app',
    measurementId: 'G-81YZWY8KCL',
  );
}
